
# travis config

sudo: required
warnings_are_errors: false

language: r
cache: packages

before_install:
  - R -e "install.packages(c('devtools','roxygen2','testthat'))"
  - R -e "devtools::install_deps('./pkg')"
  - R -e "devtools::document('./pkg')"
  - cd ./pkg
  - chmod a+w tests/testthat/write_read_ts/csv
  - chmod a+w tests/testthat/write_read_ts/xlsx

r_packages:
  - rmarkdown

notifications:
  email:
    on_success: change
    on_failure: always 


